/** Companies Harmac has delivered packaging machines to (cleared for public listing). */
export const references: string[] = [
  'Tamsin Oy',
  'JK-Tuoretalo Oy',
  'Rasilaisen Hapankaali Oy',
  'Urjalan Makeistukku Oy',
  'Makulaku Lakritsa Oy',
  'Vaanelan puutarha Oy',
  'Nature Line Cutlery Oy',
  'Feelia Oy',
  'Deliverde Puutarhat Oy',
  'Unison Coffee Oy',
  'Kauhajoen Puutarha Oy',
  'Tekslund Oy',
  'Teampac Oy',
  'Vihannes-Laitila Oy',
  'Sahlman Makeiset Oy',
  'Porokylän Leipomo Oy',
  'Pielispakari Oy',
  'Kotipellon puutarha Oy',
  'Skotlannin Maatalous Oy',
  'Data-Mate Oy',
  'HoviRuoka Oy',
  'Eläinruokatehdas Lemmikki Oy',
]
